<!DOCTYPE html>
<html lang="en"><head>
<script src="Causal_FSU_files/libs/clipboard/clipboard.min.js"></script>
<script src="Causal_FSU_files/libs/quarto-html/tabby.min.js"></script>
<script src="Causal_FSU_files/libs/quarto-html/popper.min.js"></script>
<script src="Causal_FSU_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Causal_FSU_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Causal_FSU_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Causal_FSU_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content=" Muzeeb Shaik  Kelley School of Business   Indiana University, Bloomington">
  <meta name="dcterms.date" content="2026-10-23">
  <title>Causal Identification with Observational Data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Causal_FSU_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Causal_FSU_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="Causal_FSU_files/libs/revealjs/dist/theme/quarto-b62fdef9eef7131d111377978c40676d.css">
  <link href="Causal_FSU_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Causal_FSU_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Causal_FSU_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Causal_FSU_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#FFFFFF" class="quarto-title-block center">
  <h1 class="title">Causal Identification with Observational Data</h1>
  <p class="subtitle"><br>PhD Seminar<br>Florida State University</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<br><strong>Muzeeb Shaik</strong><br> Kelley School of Business <br> Indiana University, Bloomington 
</div>
</div>
</div>

  <p class="date">October 23, 2026</p>
</section>
<section>
<section id="introduction-and-basics" class="title-slide slide level1 center">
<h1>Introduction and Basics</h1>

</section>
<section id="what-is-causality" class="slide level2">
<h2>What is Causality</h2>
<ul>
<li class="fragment">The concept that often turns research papers into casualties</li>
</ul>
<p><br></p>
<ul>
<li class="fragment">Before we get started, a quick poll (show of hands):
<ul>
<li class="fragment"><strong>Who primarily runs behavioral experiments?</strong></li>
<li class="fragment"><strong>Who primarily analyzes observational data?</strong></li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li class="fragment">Why is <code>causality</code> important in the context of business research?</li>
</ul>
<p><br></p>
<ul>
<li class="fragment">Do you think <span style="color:#990000">behavioral researchers</span> need to worry about causality?</li>
</ul>
</section></section>
<section>
<section id="what-is-causality-1" class="title-slide slide level1 center scrollable">
<h1>What is Causality</h1>
<ul>
<li class="fragment"><p>Causality is the link between a <strong>cause</strong> and an <strong>effect</strong>, and it underlies nearly every research claim.</p></li>
<li class="fragment"><p>One thing (the <strong>cause</strong>) sets another thing (the <strong>effect</strong>) in motion.</p></li>
<li class="fragment"><p>To call a relationship causal, three conditions must hold:</p>
<ol type="1">
<li class="fragment"><strong>Temporal precedence.</strong> The cause must occur <em>before</em> the effect.</li>
<li class="fragment"><strong>Concomitant variation.</strong> When the cause changes, the effect changes with it.</li>
<li class="fragment"><strong>No confounding factors.</strong> The effect cannot be explained by some other variable.</li>
</ol></li>
</ul>
</section>
<section id="the-fundamental-problem" class="slide level2">
<h2>The Fundamental Problem</h2>
<ul>
<li class="fragment"><strong>Concern.</strong> We only observe <em>one outcome</em> for any given unit.</li>
<li class="fragment"><strong>Solution.</strong> Construct a <strong>counterfactual</strong>, which is both the key to identification and its main point of vulnerability.</li>
<li class="fragment">Candidate counterfactuals:
<ul>
<li class="fragment">The same unit at an earlier point in time?</li>
<li class="fragment">Other units that were not treated?</li>
</ul></li>
</ul>
<p><br></p>
<div class="fragment">
<blockquote>
<p><em>Every causal claim rests on a comparison to what would have happened otherwise.</em></p>
</blockquote>
</div>
</section>
<section id="potential-outcomes-framework" class="slide level2">
<h2>Potential Outcomes Framework</h2>
<ul>
<li class="fragment"><p>The <code>potential outcomes framework</code> is a way to think about cause and effect.</p></li>
<li class="fragment"><p>Imagine two scenarios for each situation, with and without a <code>cause</code> (treatment, intervention, event).</p></li>
<li class="fragment"><p>Each scenario has a <code>potential outcome</code>, what would happen in each case.</p></li>
<li class="fragment"><p>We can only <code>observe one outcome</code> in reality.</p>
<ul>
<li class="fragment">Solution - <code>Counterfactuals</code></li>
</ul></li>
<li class="fragment"><p><code>Treatment Effect</code> - can only be estimated but not calculated</p>
<ul>
<li class="fragment"><sub><sup>ATE, ATT/ATET, LATE</sup></sub></li>
</ul></li>
</ul>
</section>
<section id="some-assumptions-of-the-potential-outcomes-framework" class="slide level2">
<h2>Some Assumptions of the Potential Outcomes Framework</h2>
<ul>
<li class="fragment">Stable Unit Treatment Value Assumption (<code>SUTVA</code>)
<ul>
<li class="fragment"><sub><sup> The <code>potential outcomes</code> for any unit do not vary with the treatment assigned to other units (<code>no interference</code>)</sup></sub></li>
<li class="fragment"><sub><sup>For each unit, there are no different versions of each treatment level (<code>no hidden variation of treatments</code>)</sup></sub></li>
</ul></li>
<li class="fragment">Another way of explaining <code>SUTVA</code>
<ul>
<li class="fragment"><sub><sup> <code>SUTVA</code> requires that the outcome of a particular unit depends only on the treatment to which the unit was assigned, not the treatments of other units (spillovers)</sup></sub></li>
</ul></li>
<li class="fragment">Example of a violation
<ul>
<li class="fragment"><sub><sup> Imagine an A/B test for a food delivery app that prioritizes deliveries for one group. While results might show faster deliveries for the prioritized group, it could be misleading. Since there are a limited number of drivers, prioritizing some orders can slow down deliveries for others who share those drivers. This “faster delivery” benefit wouldn’t be due solely to the new feature, but because of competition for shared resources.</sup></sub></li>
</ul></li>
</ul>
</section>
<section id="exchangeability-a.k.a.-ignorability" class="slide level2">
<h2>Exchangeability (a.k.a. Ignorability)</h2>
<ul>
<li class="fragment"><p><strong>Definition.</strong> Once we control for all confounders (X), the potential outcomes <code>Y(1)</code> and <code>Y(0)</code> are <em>independent</em> of treatment assignment <code>D</code>.</p></li>
<li class="fragment"><p><strong>Example (Marketing Context)</strong></p>
<ul>
<li class="fragment">Suppose we want to estimate the causal effect of a <strong>loyalty email campaign</strong> on customer spending.</li>
<li class="fragment">If customers who already have higher purchase intent are more likely to be targeted, naive comparisons will be biased.</li>
<li class="fragment">But if we can control for <strong>past spending, demographics, browsing activity, and seasonality</strong>, then the treated and untreated groups become <em>exchangeable</em> within those covariate profiles.</li>
</ul></li>
</ul>
<div class="fragment">
<blockquote>
<p><em>Exchangeability means that, after conditioning, treatment looks random.</em></p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="violations-of-exchangeability">Violations of Exchangeability</h3>
<ul>
<li class="fragment"><p>Omitted variables, such as unobserved brand affinity or unmeasured social influence.</p></li>
<li class="fragment"><p>Reverse causality, where treatment reacts to the outcome.</p></li>
<li class="fragment"><p>Bad controls, where including mediators (post-treatment variables) breaks the logic.</p></li>
<li class="fragment"><p><strong>Fixes</strong></p>
<ul>
<li class="fragment">Improve design (pre-treatment controls only).</li>
<li class="fragment">Use <strong>IV</strong>, <strong>DiD</strong>, or <strong>Matching</strong> to approximate random assignment.</li>
</ul></li>
</ul>
</section>
<section id="positivity-a.k.a.-overlap" class="slide level2">
<h2>Positivity (a.k.a. Overlap)</h2>
<ul>
<li class="fragment"><p><strong>Definition.</strong> Every unit has a positive probability of receiving each treatment level, <span class="math display">\[0 &lt; P(D=1 \mid X) &lt; 1\]</span> This ensures there is enough “common support” across groups.</p></li>
<li class="fragment"><p><strong>Intuition.</strong> For every type of person (covariate pattern), you can find both treated and untreated examples in your data.</p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="example-marketing-context">Example (Marketing Context)</h3>
<ul>
<li class="fragment">Suppose you want to estimate the effect of <strong>personalized discount offers</strong> on purchase conversion.</li>
<li class="fragment">If <em>all</em> high-income customers <strong>always</strong> receive offers, and <em>none</em> of the low-income customers <strong>ever</strong> do, then you cannot estimate the causal effect for high-income customers because there is no untreated comparison group.</li>
</ul>
<div class="fragment">
<blockquote>
<p><em>Without overlap, you are comparing apples to non-existent oranges.</em></p>
</blockquote>
</div>
</section>
<section class="slide level2">

<h3 id="why-positivity-matters">Why Positivity Matters</h3>
<ul>
<li class="fragment">Without overlap, your model <strong>extrapolates</strong> instead of <strong>identifying</strong>.</li>
<li class="fragment">Violation examples:
<ul>
<li class="fragment">Policy reforms that apply only to one state (need DiD or synthetic control).</li>
<li class="fragment">Ads shown only to a specific demographic.</li>
</ul></li>
<li class="fragment">Remedies:
<ul>
<li class="fragment">Trim non-overlapping observations (common support region).</li>
<li class="fragment">Redefine the population of inference.</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="end-of-theory-and-moving-to-practice" class="title-slide slide level1 center">
<h1>End of Theory and Moving to Practice</h1>

</section>
<section id="choosing-the-right-causal-method" class="slide level2">
<h2>Choosing the Right Causal Method</h2>
<img data-src="images/Flowchart.png" class="r-stretch" alt="Decision tree for choosing a causal method">
</section>
<section id="from-experiments-to-quasi-experiments" class="slide level2">
<h2>From Experiments to Quasi-Experiments</h2>
<blockquote>
<p><strong>Why this shift?</strong> Experiments are the gold standard, but in policy, marketing, and organizations, true randomization is often <strong>impractical, unethical, or impossible</strong>. Quasi-experiments let us recover credible causal effects anyway.</p>
</blockquote>
<ul>
<li class="fragment">We use <strong>observational data</strong> to approximate experimental logic.</li>
<li class="fragment">Leverage <strong>pre/post</strong> structure and <strong>plausibly exogenous</strong> variation.</li>
<li class="fragment">Trade-offs between stronger <strong>internal validity</strong> on one side and assumptions and <strong>generalizability</strong> concerns on the other.</li>
</ul>
</section>
<section id="when-randomization-isnt-feasible" class="slide level2">
<h2>When Randomization Isn’t Feasible</h2>
<div class="columns">
<div class="column" style="width:58%;">
<ul>
<li class="fragment"><p><strong>Impractical.</strong> You cannot reprice <strong>half</strong> your national chain at random.</p></li>
<li class="fragment"><p><strong>Unethical.</strong> You cannot randomly <strong>deny</strong> a health benefit to customers.</p></li>
<li class="fragment"><p><strong>Impossible.</strong> Policy shocks happen <strong>to you</strong>, not by you.</p></li>
<li class="fragment"><p><strong>Examples</strong></p>
<ul>
<li class="fragment">Citywide tax change; statewide minimum-wage hike</li>
<li class="fragment">Algorithm change rolled out by platform</li>
<li class="fragment">Loyalty tier thresholds or grant cutoffs</li>
</ul></li>
</ul>
</div><div class="column" style="width:42%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="https://images.unsplash.com/photo-1508385082359-f38ae991e8f2?q=80&amp;w=1200.png" class="quarto-figure quarto-figure-center" style="width:75.0%"></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="matching-approaches" class="title-slide slide level1 center">
<h1>Matching Approaches</h1>

</section>
<section id="selection-on-observables" class="slide level2">
<h2>Selection on Observables</h2>
<ul>
<li class="fragment">Matching estimators take <strong>exchangeability</strong> and <strong>positivity</strong> as their identifying assumptions.
<ul>
<li class="fragment">Exchangeability, <span class="math inline">\(\{Y(1), Y(0)\} \perp D \mid X\)</span>, means we observe <em>every</em> confounder.</li>
<li class="fragment">Positivity, <span class="math inline">\(0 &lt; P(D=1 \mid X) &lt; 1\)</span>, means comparable treated and untreated units exist.</li>
</ul></li>
<li class="fragment">Matching makes treated and control groups look alike <strong>on observed covariates</strong>.</li>
<li class="fragment">It does <strong>not</strong> address unobserved confounders. Its credibility depends on the argument for why <span class="math inline">\(X\)</span> is sufficient.</li>
</ul>
</section>
<section id="why-not-just-regression" class="slide level2">
<h2>Why Not Just Regression?</h2>
<ul>
<li class="fragment">Regression also “controls for” <span class="math inline">\(X\)</span>, but it
<ul>
<li class="fragment">imposes a functional form (usually linear and additive),</li>
<li class="fragment">extrapolates silently into regions with no overlap, and</li>
<li class="fragment">mixes design and analysis, since balance is never checked.</li>
</ul></li>
<li class="fragment">Matching and weighting separate the <strong>design stage</strong> (build a comparable sample, check balance) from the <strong>analysis stage</strong> (estimate the effect).</li>
</ul>
<div class="fragment">
<blockquote>
<p><em>Design the study before you look at the outcome</em> (Rubin 2008).</p>
</blockquote>
</div>
</section>
<section id="running-example-a-b2b-engagement-app" class="slide level2">
<h2>Running Example: A B2B Engagement App</h2>
<ul>
<li class="fragment">Gill, Sridhar, and Grewal (2017, <em>Journal of Marketing</em>)</li>
<li class="fragment">A tool manufacturer launches a <strong>free mobile app</strong> that helps buyers search for tools and design machining processes.
<ul>
<li class="fragment">The app is not a sales channel. Does it still raise purchases?</li>
</ul></li>
<li class="fragment">The firm could not randomize, because for fairness the app was available to every buyer.</li>
<li class="fragment"><strong>Data.</strong> 522 buyers that adopted the app and 626 that did not; sales in the 15 months before and after launch.</li>
<li class="fragment"><strong>Selection concern.</strong> Buyers adopt strategically, expecting cost savings. Frequent, powerful buyers are both more likely to adopt and more valuable to begin with.</li>
</ul>
</section>
<section id="what-drives-adoption" class="slide level2">
<h2>What Drives Adoption?</h2>
<p>From interviews with the app team, the authors identify covariates that proxy for buyers’ expected cost savings.</p>
<ul>
<li class="fragment"><strong>Buyer power</strong>, the buyer’s share of the seller’s sales in its division</li>
<li class="fragment"><strong>Buyer firm size</strong> (employees)</li>
<li class="fragment"><strong>Buyer industry competitiveness</strong> (1 minus the concentration ratio)</li>
<li class="fragment"><strong>T0 sales and T0 purchase frequency</strong>, in the five months before the pre-period</li>
<li class="fragment"><strong>Continent and industry division</strong></li>
</ul>
<div class="fragment">
<p>In the paper, adopters made almost twice as many T0 purchases as nonadopters (97 vs.&nbsp;51, <span class="math inline">\(t = -5.91\)</span>).</p>
</div>
</section>
<section id="our-simulated-version" class="slide level2 smaller">
<h2>Our Simulated Version</h2>
<ul>
<li class="fragment">We simulate 1,148 buyers whose covariates, sales, and adoption mirror the paper’s Table 4 and Figure 1.</li>
<li class="fragment">Adoption depends <strong>only on observed covariates</strong> (selection on observables holds by construction).</li>
<li class="fragment">Buyers who purchase frequently are more likely to adopt <strong>and</strong> on a steeper sales path even without the app.</li>
<li class="fragment">Because we generated the data, we <strong>know the true effect</strong>.</li>
</ul>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Pre-launch sales</th>
<th style="text-align: right;">Post-launch sales</th>
<th style="text-align: right;">Change</th>
<th style="text-align: right;">T0 frequency</th>
<th style="text-align: right;">Buyer power</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nonadopters (626)</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: right;">74.6</td>
<td style="text-align: right;">−3.0</td>
<td style="text-align: right;">48.4</td>
<td style="text-align: right;">51.8</td>
</tr>
<tr class="even">
<td>Adopters (522)</td>
<td style="text-align: right;">83.0</td>
<td style="text-align: right;">105.1</td>
<td style="text-align: right;">22.1</td>
<td style="text-align: right;">88.6</td>
<td style="text-align: right;">81.5</td>
</tr>
</tbody>
</table>
<p><sub><sup>Sales in $10,000. Outcome used throughout is the change in sales, post minus pre.</sup></sub></p>
</div>
</section>
<section id="the-naive-estimate" class="slide level2">
<h2>The Naive Estimate</h2>
<ul>
<li class="fragment">Compare the change in sales for adopters and nonadopters, <span class="math display">\[\widehat{\tau}_{naive} = 22.1 - (-3.0) = 25.1\]</span></li>
<li class="fragment">Is this the effect of the app?</li>
<li class="fragment">Adopters differed <strong>before</strong> the launch. Their T0 purchase frequency has a standardized difference of 1.16, and buyer power 0.82.</li>
<li class="fragment">Frequent buyers were going to grow faster anyway, so part of the 25.1 is <strong>selection</strong>, not the app.</li>
</ul>
</section>
<section id="the-propensity-score" class="slide level2">
<h2>The Propensity Score</h2>
<ul>
<li class="fragment"><strong>Definition.</strong> The probability of treatment given covariates, <span class="math display">\[e(X) = P(D = 1 \mid X)\]</span></li>
<li class="fragment"><strong>Key result</strong> (Rosenbaum and Rubin 1983). If exchangeability holds given <span class="math inline">\(X\)</span>, it also holds given <span class="math inline">\(e(X)\)</span>.
<ul>
<li class="fragment">Units with the same propensity score have the same distribution of <span class="math inline">\(X\)</span>, whether treated or not.</li>
</ul></li>
<li class="fragment"><strong>Dimension reduction.</strong> Instead of matching on many covariates, we match or weight on a single number.</li>
<li class="fragment">In practice <span class="math inline">\(e(X)\)</span> is unknown and estimated, usually with a logit or probit.
<ul>
<li class="fragment">In the example, <span class="math inline">\(e(X)\)</span> is a buyer’s probability of adopting the app.</li>
</ul></li>
</ul>
</section>
<section id="att-vs.-ate" class="slide level2 smaller">
<h2>ATT vs.&nbsp;ATE</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="ate">ATE</h3>
<p><span class="math display">\[E[Y(1) - Y(0)]\]</span></p>
<ul>
<li class="fragment">Average effect across <strong>all</strong> units, treated or not.</li>
<li class="fragment">Answers “what if we rolled the app out to <strong>every</strong> buyer?”</li>
<li class="fragment">Requires comparable treated units for every control, and vice versa.</li>
<li class="fragment">Stata: <code>teffects ...</code> (default)</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="att">ATT</h3>
<p><span class="math display">\[E[Y(1) - Y(0) \mid D = 1]\]</span></p>
<ul>
<li class="fragment">Average effect among units that <strong>actually received</strong> treatment.</li>
<li class="fragment">Answers “did the app pay off for the buyers who <strong>adopted</strong>?”</li>
<li class="fragment">Requires comparable controls for the treated only.</li>
<li class="fragment">Stata: <code>teffects ..., atet</code></li>
</ul>
</div></div>
<div class="fragment">
<ul>
<li class="fragment">The two are equal only if effects are homogeneous, or if treated and untreated units have the same mix of effects.</li>
<li class="fragment">In the example, the effect grows with purchase frequency and frequent buyers adopt, so <strong>ATT = 15.85 &gt; ATE = 14.63</strong>.</li>
</ul>
</div>
</section>
<section id="two-ways-to-use-the-propensity-score" class="slide level2">
<h2>Two Ways to Use the Propensity Score</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="matching-psm">Matching (PSM)</h3>
<ul>
<li class="fragment">Pair each adopter with nonadopter(s) of similar <span class="math inline">\(e(X)\)</span>.</li>
<li class="fragment">Discard unmatched units.</li>
<li class="fragment">Natural target is the <strong>ATT</strong>, the effect for buyers who adopted.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="weighting-ipw">Weighting (IPW)</h3>
<ul>
<li class="fragment">Keep every buyer, but weight by the inverse of the probability of the choice actually made.</li>
<li class="fragment">Creates a pseudo-population in which adoption is independent of <span class="math inline">\(X\)</span>.</li>
<li class="fragment">Targets the <strong>ATE</strong> or the <strong>ATT</strong>, depending on the weights.</li>
</ul>
</div></div>
</section></section>
<section>
<section id="propensity-score-matching" class="title-slide slide level1 center">
<h1>Propensity Score Matching</h1>

</section>
<section id="psm-in-four-steps" class="slide level2 scrollable">
<h2>PSM in Four Steps</h2>
<ol type="1">
<li class="fragment"><strong>Estimate</strong> the propensity score (logit or probit on pre-treatment covariates).</li>
<li class="fragment"><strong>Match</strong> treated units to controls with similar scores.</li>
<li class="fragment"><strong>Check balance</strong> on every covariate in the matched sample.
<ul>
<li class="fragment">If balance is poor, revise the score model (logs, interactions, polynomials) and return to step 1.</li>
</ul></li>
<li class="fragment"><strong>Estimate</strong> the treatment effect in the matched sample.</li>
</ol>
<div class="fragment">
<blockquote>
<p><em>Steps 1 to 3 never touch the outcome variable.</em></p>
</blockquote>
</div>
</section>
<section id="matching-choices" class="slide level2 smaller">
<h2>Matching Choices</h2>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 32%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Choice</th>
<th>Options</th>
<th>Trade-off</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of matches</td>
<td>1 nearest neighbor, <span class="math inline">\(k\)</span> neighbors</td>
<td>More neighbors lower variance but raise bias</td>
</tr>
<tr class="even">
<td>Replacement</td>
<td>With, without</td>
<td>With replacement lowers bias; reused controls raise variance</td>
</tr>
<tr class="odd">
<td>Caliper</td>
<td>None, maximum distance</td>
<td>A caliper drops poor matches but can drop treated units, changing the estimand</td>
</tr>
<tr class="even">
<td>Distance</td>
<td>Propensity score, Mahalanobis</td>
<td>Mahalanobis matches on covariates directly; works well with few covariates</td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">A common caliper is 0.2 standard deviations of the <strong>logit</strong> of the propensity score (Austin 2011).</li>
<li class="fragment">Gill et al.&nbsp;(2017) report nearest-neighbor matching with Mahalanobis, inverse-variance, and Euclidean distances, and with one to three neighbors.</li>
</ul>
</section>
<section id="checking-overlap" class="slide level2">
<h2>Checking Overlap</h2>

<img data-src="images/app_overlap.png" class="r-stretch quarto-figure quarto-figure-center" alt="Kernel densities of the estimated propensity score for adopters and nonadopters"><ul>
<li class="fragment">Few nonadopters have scores above 0.8, where many adopters sit. Those adopters are matched to the same few controls.</li>
</ul>
</section>
<section id="checking-balance" class="slide level2">
<h2>Checking Balance</h2>
<ul>
<li class="fragment"><strong>Standardized mean difference</strong> for covariate <span class="math inline">\(X_k\)</span>, <span class="math display">\[SMD_k = \frac{\bar{X}_{k,T} - \bar{X}_{k,C}}{\sqrt{(s^2_{k,T} + s^2_{k,C})/2}}\]</span>
<ul>
<li class="fragment">Rule of thumb: <span class="math inline">\(|SMD| &lt; 0.1\)</span> after matching.</li>
</ul></li>
<li class="fragment"><strong>Variance ratio</strong> <span class="math inline">\(s^2_{k,T}/s^2_{k,C}\)</span> close to 1.</li>
<li class="fragment">Compare the <strong>full distribution</strong>, not only the means.</li>
<li class="fragment">Do <strong>not</strong> use <span class="math inline">\(t\)</span>-tests for balance, since they depend on sample size, which matching changes.</li>
</ul>
</section>
<section id="balance-in-the-example" class="slide level2 smaller">
<h2>Balance in the Example</h2>
<div class="columns">
<div class="column" style="width:45%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Covariate</th>
<th style="text-align: right;">Raw SMD</th>
<th style="text-align: right;">Matched SMD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Log firm size</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td>Log buyer power</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="odd">
<td>Competitiveness</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="even">
<td>Log T0 sales</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.06</td>
</tr>
<tr class="odd">
<td>Log T0 frequency</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td>Developing economy</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.07</td>
</tr>
<tr class="odd">
<td>General engineering</td>
<td style="text-align: right;">−0.10</td>
<td style="text-align: right;">0.16</td>
</tr>
</tbody>
</table>
<p><sub><sup>One nearest neighbor, ATT. Skewed covariates enter the score in logs; in levels, the variance ratios for firm size (0.52) and T0 frequency (1.52) stay far from 1.</sup></sub></p>
</div><div class="column" style="width:55%;">
<p><img data-src="images/app_balance_freq.png" style="width:100.0%" alt="Density of log T0 purchase frequency for adopters and nonadopters before and after matching"></p>
</div></div>
</section>
<section id="psm-in-stata" class="slide level2">
<h2>PSM in Stata</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href=""></a>* Load the <span class="kw">data</span> and <span class="fu">log</span> the skewed covariates</span>
<span id="cb1-2"><a href=""></a><span class="kw">use</span> app_adoption, <span class="kw">clear</span></span>
<span id="cb1-3"><a href=""></a><span class="kw">generate</span> ln_size  = <span class="fu">ln</span>(firm_size)</span>
<span id="cb1-4"><a href=""></a><span class="kw">generate</span> ln_power = <span class="fu">ln</span>(buyer_power)</span>
<span id="cb1-5"><a href=""></a><span class="kw">generate</span> ln_sales = <span class="fu">ln</span>(t0_sales)</span>
<span id="cb1-6"><a href=""></a><span class="kw">generate</span> ln_freq  = <span class="fu">ln</span>(t0_freq)</span>
<span id="cb1-7"><a href=""></a></span>
<span id="cb1-8"><a href=""></a>* PSM, ATT, one nearest neighbor (teffects fits the <span class="kw">logit</span> <span class="kw">in</span> the 2nd parentheses)</span>
<span id="cb1-9"><a href=""></a>teffects psmatch (dsales) <span class="co">///</span></span>
<span id="cb1-10"><a href=""></a>    (app ln_size ln_power competitiveness ln_sales ln_freq i.developing i.division), <span class="co">///</span></span>
<span id="cb1-11"><a href=""></a>    atet</span>
<span id="cb1-12"><a href=""></a></span>
<span id="cb1-13"><a href=""></a>* Balance: standardized differences near 0, <span class="kw">variance</span> ratios near 1</span>
<span id="cb1-14"><a href=""></a>tebalance <span class="kw">summarize</span></span>
<span id="cb1-15"><a href=""></a>tebalance density ln_freq</span>
<span id="cb1-16"><a href=""></a></span>
<span id="cb1-17"><a href=""></a>* Variations: add nneighbor(3) <span class="kw">or</span> caliper(0.1) after atet</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li class="fragment"><code>teffects</code> reports Abadie and Imbens (2016) standard errors, which account for the estimated propensity score.</li>
</ul>
</section>
<section id="cautions-about-psm" class="slide level2">
<h2>Cautions About PSM</h2>
<ul>
<li class="fragment"><strong>Model dependence.</strong> Results can change with the score specification, the number of neighbors, and the caliper. Report several, as Gill et al.&nbsp;(2017) do.</li>
<li class="fragment"><strong>The PSM paradox</strong> (King and Nielsen 2019). With good balance already, further pruning on the score can <em>increase</em> imbalance and model dependence.</li>
<li class="fragment"><strong>Discarded data.</strong> Matching without replacement or with a tight caliper changes the population you are describing.</li>
<li class="fragment"><strong>Inference.</strong> Bootstrapping nearest-neighbor matching estimators is invalid (Abadie and Imbens 2008). Use the analytic standard errors.</li>
</ul>
</section></section>
<section>
<section id="inverse-probability-weighting" class="title-slide slide level1 center">
<h1>Inverse Probability Weighting</h1>

</section>
<section id="the-idea" class="slide level2">
<h2>The Idea</h2>
<ul>
<li class="fragment">Adopters who <em>looked unlikely</em> to adopt resemble nonadopters, so they get <strong>more weight</strong>, and likewise for nonadopters who looked likely to adopt.</li>
<li class="fragment"><strong>ATE weights</strong> <span class="math display">\[w_i = \frac{D_i}{\hat{e}(X_i)} + \frac{1 - D_i}{1 - \hat{e}(X_i)}\]</span></li>
<li class="fragment"><strong>ATT weights.</strong> Adopters get weight 1; nonadopters get <span class="math inline">\(\hat{e}(X_i)/(1 - \hat{e}(X_i))\)</span>, so nonadopters who look like adopters count more.</li>
<li class="fragment">The estimate is a weighted difference in means, <span class="math display">\[\hat{\tau}_{IPW} = \frac{\sum_i w_i D_i Y_i}{\sum_i w_i D_i} - \frac{\sum_i w_i (1 - D_i) Y_i}{\sum_i w_i (1 - D_i)}\]</span></li>
</ul>
</section>
<section id="extreme-weights" class="slide level2">
<h2>Extreme Weights</h2>
<ul>
<li class="fragment">When <span class="math inline">\(\hat{e}(X)\)</span> is close to 0 or 1, weights explode and a handful of units drive the estimate.
<ul>
<li class="fragment">This is a <strong>positivity problem</strong> showing up in the estimator.</li>
<li class="fragment">In the example, the median ATE weight is 1.5 but the largest is 19.3.</li>
</ul></li>
<li class="fragment">Remedies
<ul>
<li class="fragment"><strong>Inspect</strong> the weight distribution (maximum, top percentiles).</li>
<li class="fragment"><strong>Trim</strong> the sample to <span class="math inline">\(0.1 \le \hat{e}(X) \le 0.9\)</span> (Crump et al.&nbsp;2009), which redefines the estimand.</li>
<li class="fragment"><strong>Stabilize</strong> weights by multiplying by the marginal probability of treatment.</li>
<li class="fragment"><strong>Normalize</strong> weights to sum to one within each group (as in the formula above).</li>
</ul></li>
</ul>
</section>
<section id="doubly-robust-estimators" class="slide level2">
<h2>Doubly Robust Estimators</h2>
<ul>
<li class="fragment">Combine a <strong>treatment model</strong> for <span class="math inline">\(e(X)\)</span> with an <strong>outcome model</strong> for <span class="math inline">\(E[Y \mid X, D]\)</span>.</li>
<li class="fragment">The estimate is consistent if <strong>either</strong> model is correctly specified.</li>
<li class="fragment"><strong>IPWRA.</strong> Weighted regression adjustment, with outcome models fit using IPW weights.</li>
<li class="fragment"><strong>AIPW.</strong> The IPW estimate plus an augmentation term built from the outcome model.</li>
<li class="fragment">In practice, a sensible default, and a useful check on PSM and IPW.</li>
</ul>
</section>
<section id="ipw-in-stata" class="slide level2">
<h2>IPW in Stata</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href=""></a>* IPW, ATT (<span class="kw">drop</span> atet <span class="kw">for</span> the ATE)</span>
<span id="cb2-2"><a href=""></a>teffects ipw (dsales) <span class="co">///</span></span>
<span id="cb2-3"><a href=""></a>    (app ln_size ln_power competitiveness ln_sales ln_freq i.developing i.division), <span class="co">///</span></span>
<span id="cb2-4"><a href=""></a>    atet</span>
<span id="cb2-5"><a href=""></a></span>
<span id="cb2-6"><a href=""></a>* Balance <span class="kw">in</span> the weighted <span class="kw">sample</span>, and the overlap plot</span>
<span id="cb2-7"><a href=""></a>tebalance <span class="kw">summarize</span></span>
<span id="cb2-8"><a href=""></a>teoverlap</span>
<span id="cb2-9"><a href=""></a></span>
<span id="cb2-10"><a href=""></a>* Doubly <span class="kw">robust</span>, IPWRA: 1st parentheses = outcome <span class="kw">model</span>, 2nd = treatment <span class="kw">model</span></span>
<span id="cb2-11"><a href=""></a>teffects ipwra <span class="co">///</span></span>
<span id="cb2-12"><a href=""></a>    (dsales firm_size buyer_power competitiveness t0_sales t0_freq i.developing i.division) <span class="co">///</span></span>
<span id="cb2-13"><a href=""></a>    (app ln_size ln_power competitiveness ln_sales ln_freq i.developing i.division), <span class="co">///</span></span>
<span id="cb2-14"><a href=""></a>    atet</span>
<span id="cb2-15"><a href=""></a></span>
<span id="cb2-16"><a href=""></a>* Doubly <span class="kw">robust</span>, AIPW (ATE): <span class="kw">replace</span> ipwra with aipw and <span class="kw">drop</span> atet</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li class="fragment">After weighting, every standardized difference in the example is below 0.04.</li>
<li class="fragment">Weighting by hand (<code>regress dsales i.app [pw = w]</code>) gives the same point estimate, but its standard errors ignore that <span class="math inline">\(\hat{e}(X)\)</span> was estimated.</li>
</ul>
</section></section>
<section>
<section id="matching-results-and-limits" class="title-slide slide level1 center">
<h1>Matching: Results and Limits</h1>

</section>
<section id="comparing-estimators" class="slide level2 smaller">
<h2>Comparing Estimators</h2>
<p>Effect of app adoption on the change in 15-month sales ($10,000)</p>
<div class="columns">
<div class="column" style="width:55%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Estimator</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Naive difference</td>
<td style="text-align: right;">25.08</td>
<td style="text-align: right;">1.43</td>
</tr>
<tr class="even">
<td>Regression adjustment (ATT)</td>
<td style="text-align: right;">15.18</td>
<td style="text-align: right;">1.71</td>
</tr>
<tr class="odd">
<td>PSM, 1 neighbor (ATT)</td>
<td style="text-align: right;">15.42</td>
<td style="text-align: right;">2.11</td>
</tr>
<tr class="even">
<td>PSM, 3 neighbors (ATT)</td>
<td style="text-align: right;">15.45</td>
<td style="text-align: right;">2.01</td>
</tr>
<tr class="odd">
<td>IPW (ATT)</td>
<td style="text-align: right;">14.76</td>
<td style="text-align: right;">1.85</td>
</tr>
<tr class="even">
<td>IPWRA (ATT)</td>
<td style="text-align: right;">14.74</td>
<td style="text-align: right;">1.58</td>
</tr>
<tr class="odd">
<td>IPW (ATE)</td>
<td style="text-align: right;">15.36</td>
<td style="text-align: right;">1.64</td>
</tr>
<tr class="even">
<td>AIPW (ATE)</td>
<td style="text-align: right;">14.93</td>
<td style="text-align: right;">1.58</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<div class="fragment">
<p><strong>The truth</strong> (known only because we simulated)</p>
<ul>
<li class="fragment">True ATT = <strong>15.85</strong></li>
<li class="fragment">True ATE = <strong>14.63</strong></li>
</ul>
</div>
<div class="fragment">
<ul>
<li class="fragment">The naive estimate overstates the effect by almost 60%.</li>
<li class="fragment">Every adjusted estimate is within one standard error of the truth.</li>
<li class="fragment">Gill et al.&nbsp;(2017) report 15.3 to 18.3 across matching, IPW, and IPWRA.</li>
</ul>
</div>
</div></div>
</section>
<section id="unobserved-confounding" class="slide level2 smaller">
<h2>Unobserved Confounding</h2>
<ul>
<li class="fragment">Every estimator here assumes <strong>no unobserved confounders</strong>. Balance on <span class="math inline">\(X\)</span> says nothing about balance on what you did not measure.
<ul>
<li class="fragment">In our simulation this holds by construction. In real data it is an argument, not a fact.</li>
</ul></li>
<li class="fragment">Gill et al.&nbsp;(2017) address it with a <strong>Heckman selection model</strong>, using the number of buying units as an exclusion restriction (it shifts adoption but not sales).</li>
<li class="fragment">Other ways to assess sensitivity
<ul>
<li class="fragment"><strong>Rosenbaum bounds.</strong> How strong would hidden bias have to be to overturn the result?</li>
<li class="fragment"><strong>E-values</strong> (VanderWeele and Ding 2017). The minimum association an unmeasured confounder would need with both treatment and outcome.</li>
<li class="fragment"><strong>Coefficient stability</strong> (Oster 2019). How much selection on unobservables, relative to observables, would drive the effect to zero?</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="instrumental-variables" class="title-slide slide level1 center">
<h1>Instrumental Variables</h1>

</section>
<section id="when-selection-is-on-unobservables" class="slide level2">
<h2>When Selection Is on Unobservables</h2>
<ul>
<li class="fragment">Matching and weighting assume we observe <strong>every</strong> confounder.</li>
<li class="fragment">Often a confounder <span class="math inline">\(U\)</span> is unobserved and affects both treatment <span class="math inline">\(D\)</span> and outcome <span class="math inline">\(Y\)</span>.
<ul>
<li class="fragment">Balancing <span class="math inline">\(X\)</span> does nothing about <span class="math inline">\(U\)</span>, so OLS, PSM, and IPW are all biased.</li>
</ul></li>
<li class="fragment"><strong>Idea.</strong> Find a source of variation in <span class="math inline">\(D\)</span> that is unrelated to <span class="math inline">\(U\)</span>, and use <strong>only</strong> that variation to estimate the effect.</li>
<li class="fragment">That source of variation is an <strong>instrument</strong> <span class="math inline">\(Z\)</span>.</li>
</ul>
</section>
<section id="the-iv-idea" class="slide level2">
<h2>The IV Idea</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/iv_dag.svg" class="quarto-figure quarto-figure-center" style="width:78.0%" alt="Causal diagram: instrument Z affects treatment D, which affects outcome Y; an unobserved shock U affects D and Y; there is no direct path from Z to Y and no link between U and Z"></p>
</figure>
</div>
<ul>
<li class="fragment">Only the part of <span class="math inline">\(D\)</span> driven by <span class="math inline">\(Z\)</span> is used, and that part is free of <span class="math inline">\(U\)</span>.</li>
</ul>
</section>
<section id="three-conditions-for-a-valid-instrument" class="slide level2 scrollable">
<h2>Three Conditions for a Valid Instrument</h2>
<ol type="1">
<li class="fragment"><strong>Relevance.</strong> <span class="math inline">\(Z\)</span> is correlated with <span class="math inline">\(D\)</span>, conditional on controls.
<ul>
<li class="fragment">Testable with the first stage.</li>
</ul></li>
<li class="fragment"><strong>Exclusion.</strong> <span class="math inline">\(Z\)</span> affects <span class="math inline">\(Y\)</span> <strong>only</strong> through <span class="math inline">\(D\)</span>.
<ul>
<li class="fragment">Not testable. It must be argued from institutional knowledge.</li>
</ul></li>
<li class="fragment"><strong>Independence.</strong> <span class="math inline">\(Z\)</span> is as good as randomly assigned, so it is unrelated to <span class="math inline">\(U\)</span>.
<ul>
<li class="fragment">Not testable either; supported by the design.</li>
</ul></li>
</ol>
<div class="fragment">
<ul>
<li class="fragment">With heterogeneous effects (and monotonicity), IV estimates a <strong>local average treatment effect (LATE)</strong>, the effect for units whose treatment responds to <span class="math inline">\(Z\)</span> (Imbens and Angrist 1994).</li>
</ul>
</div>
</section>
<section id="two-stage-least-squares-2sls" class="slide level2">
<h2>Two-Stage Least Squares (2SLS)</h2>
<ul>
<li class="fragment"><strong>First stage.</strong> Regress the endogenous variable on the instruments and controls, <span class="math display">\[D_i = \pi_0 + \pi_1 Z_i + X_i'\gamma + v_i\]</span></li>
<li class="fragment"><strong>Second stage.</strong> Replace <span class="math inline">\(D_i\)</span> with its fitted value <span class="math inline">\(\hat{D}_i\)</span>, <span class="math display">\[Y_i = \beta_0 + \beta_1 \hat{D}_i + X_i'\delta + \varepsilon_i\]</span></li>
<li class="fragment">With one instrument, 2SLS is a ratio of two regressions, <span class="math display">\[\hat{\beta}_1 = \frac{\text{effect of } Z \text{ on } Y \text{ (reduced form)}}{\text{effect of } Z \text{ on } D \text{ (first stage)}}\]</span></li>
<li class="fragment">Running the two stages by hand gives the right estimate but the <strong>wrong standard errors</strong>. Use <code>ivregress</code>.</li>
</ul>
</section>
<section id="running-example-herding-in-ad-spending-disclosure" class="slide level2">
<h2>Running Example: Herding in Ad Spending Disclosure</h2>
<ul>
<li class="fragment">Shi, Grewal, and Sridhar (2021, <em>Journal of Marketing Research</em>)</li>
<li class="fragment">A 1994 rule made disclosing advertising spending <strong>voluntary</strong> for U.S. firms. The share of firms disclosing fell sharply.</li>
<li class="fragment"><strong>Question.</strong> Do firms copy (herd on) their peers’ disclosure decisions?</li>
<li class="fragment"><strong>Model.</strong> A linear probability model for 48,509 firm-years, <span class="math display">\[d_{it} = \alpha + \beta\, PeerDisclosure_{it} + \delta x_{it} + \gamma PEERGROUP_{it} + \text{Industry} \times \text{Year} + e_{it}\]</span>
<ul>
<li class="fragment"><span class="math inline">\(d_{it} = 1\)</span> if firm <span class="math inline">\(i\)</span> discloses in year <span class="math inline">\(t\)</span>; <span class="math inline">\(PeerDisclosure_{it}\)</span> is the share of its peers that disclose.</li>
</ul></li>
</ul>
</section>
<section id="why-peer-disclosure-is-endogenous" class="slide level2">
<h2>Why Peer Disclosure Is Endogenous</h2>
<ul>
<li class="fragment"><strong>Reflection problem</strong> (Manski 1993). If a firm and its peers share exactly the same peer group, the peer average is a linear function of the group’s own traits and <span class="math inline">\(\beta\)</span> is not identified.
<ul>
<li class="fragment">The paper uses <strong>partially overlapping peer groups</strong> (firms operate in several industries) to break this.</li>
</ul></li>
<li class="fragment"><strong>Correlated unobservables.</strong> A shock common to a firm and its peers (for example, a change in how investors in their markets react to ad disclosures) makes them all disclose.
<ul>
<li class="fragment">OLS attributes the common shock to herding, so <span class="math inline">\(\hat{\beta}_{OLS}\)</span> is <strong>too large</strong>.</li>
</ul></li>
<li class="fragment">In the paper, OLS gives <strong>0.912</strong> and 2SLS gives <strong>0.483</strong>.</li>
</ul>
</section>
<section id="the-instruments-second-degree-peers" class="slide level2">
<h2>The Instruments: Second-Degree Peers</h2>
<ul>
<li class="fragment"><strong>Second-degree peers</strong> are the peers of a firm’s peers who are not its own peers.
<ul>
<li class="fragment">Apple’s peer Dell also competes in cybersecurity, so Dell’s peers include NetWolves, which is not Apple’s peer.</li>
</ul></li>
<li class="fragment"><strong>Instruments.</strong> Average size, SG&amp;A dummy, ROA, and Big Six auditor of second-degree peers.</li>
<li class="fragment"><strong>Relevance.</strong> NetWolves’ traits shape NetWolves’ disclosure, which influences Dell’s, which Apple observes.</li>
<li class="fragment"><strong>Exclusion.</strong> NetWolves is outside Apple’s peer group, so its traits should be unrelated to shocks that hit Apple and its peers.</li>
<li class="fragment">Four instruments for one endogenous variable, so the model is <strong>overidentified</strong> and can be tested (Hansen’s <span class="math inline">\(J\)</span>).</li>
</ul>
</section>
<section id="our-simulated-version-1" class="slide level2 smaller">
<h2>Our Simulated Version</h2>
<ul>
<li class="fragment">1,500 firms observed for 10 years (15,000 firm-years), with the paper’s variables.</li>
<li class="fragment">An <strong>unobserved common shock</strong> raises both the firm’s and its peers’ disclosure.</li>
<li class="fragment">Second-degree peer traits move peer disclosure but are unrelated to the shock.</li>
<li class="fragment"><strong>True herding effect.</strong> A slope of 0.48; averaged over firm-years (a few sit at a probability of 0), the true effect is <strong>0.46</strong>.</li>
<li class="fragment">We add two bad instruments for teaching
<ul>
<li class="fragment"><strong>Weak.</strong> ROA of second-degree peers alone (barely moves peer disclosure).</li>
<li class="fragment"><strong>Invalid.</strong> An industry advertising trend driven by the same unobserved shock.</li>
</ul></li>
</ul>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Disclose</th>
<th style="text-align: right;">Peer disclosure</th>
<th style="text-align: right;">Size</th>
<th style="text-align: right;">SG&amp;A dummy</th>
<th style="text-align: right;">ROA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simulated</td>
<td style="text-align: right;">0.264</td>
<td style="text-align: right;">0.273</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">0.834</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="even">
<td>Paper (Table 2)</td>
<td style="text-align: right;">0.274</td>
<td style="text-align: right;">0.273</td>
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">0.855</td>
<td style="text-align: right;">0.030</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="the-first-stage" class="slide level2 smaller">
<h2>The First Stage</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p>Dependent variable: share of peers disclosing</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Instrument</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Size, 2nd-degree peers</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td>SG&amp;A, 2nd-degree peers</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.016</td>
</tr>
<tr class="odd">
<td>ROA, 2nd-degree peers</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.032</td>
</tr>
<tr class="even">
<td>Big Six, 2nd-degree peers</td>
<td style="text-align: right;">0.222</td>
<td style="text-align: right;">0.027</td>
</tr>
<tr class="odd">
<td><strong>Joint F (4, 1499)</strong></td>
<td style="text-align: right;"><strong>32.3</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><sub><sup>Controls and industry and year fixed effects included; SEs clustered by firm. Paper: F = 29.23, three of four instruments significant.</sup></sub></p>
</div><div class="column" style="width:55%;">
<ul>
<li class="fragment"><strong>Weak instruments</strong> bias 2SLS toward OLS and make standard errors and tests unreliable.</li>
<li class="fragment">Rules of thumb for the first-stage F
<ul>
<li class="fragment">Above <strong>10</strong> (Staiger and Stock 1997)</li>
<li class="fragment">Compare with Stock and Yogo (2005) critical values</li>
<li class="fragment">Above <strong>104.7</strong>, with one instrument, for a conventional 5% <span class="math inline">\(t\)</span>-test to have correct size (Lee et al.&nbsp;2022)</li>
</ul></li>
<li class="fragment">A strong first stage establishes relevance only. It says nothing about exclusion.</li>
</ul>
</div></div>
</section>
<section id="iv-in-stata" class="slide level2">
<h2>IV in Stata</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href=""></a><span class="kw">use</span> disclosure_panel, <span class="kw">clear</span></span>
<span id="cb3-2"><a href=""></a></span>
<span id="cb3-3"><a href=""></a>* 2SLS: outcome (endogenous = instruments) controls</span>
<span id="cb3-4"><a href=""></a>ivregress 2sls disclose <span class="co">///</span></span>
<span id="cb3-5"><a href=""></a>    (peer_disc = size_2nd sga_2nd roa_2nd big6_2nd) <span class="co">///</span></span>
<span id="cb3-6"><a href=""></a>    <span class="kw">size</span> sga roa rd big6 size_peer sga_peer roa_peer big6_peer <span class="co">///</span></span>
<span id="cb3-7"><a href=""></a>    i.industry i.<span class="fu">year</span>, <span class="kw">vce</span>(<span class="kw">cluster</span> firm_id)</span>
<span id="cb3-8"><a href=""></a></span>
<span id="cb3-9"><a href=""></a><span class="kw">estat</span> firststage      <span class="co">// partial R-squared and first-stage F</span></span>
<span id="cb3-10"><a href=""></a><span class="kw">estat</span> endogenous      <span class="co">// does IV differ from OLS?</span></span>
<span id="cb3-11"><a href=""></a></span>
<span id="cb3-12"><a href=""></a>* GMM <span class="kw">version</span>, <span class="kw">for</span> Hansen's <span class="fu">J</span> overidentification <span class="kw">test</span></span>
<span id="cb3-13"><a href=""></a>ivregress gmm disclose (peer_disc = size_2nd sga_2nd roa_2nd big6_2nd) <span class="co">///</span></span>
<span id="cb3-14"><a href=""></a>    <span class="kw">size</span> sga roa rd big6 size_peer sga_peer roa_peer big6_peer <span class="co">///</span></span>
<span id="cb3-15"><a href=""></a>    i.industry i.<span class="fu">year</span>, <span class="kw">vce</span>(<span class="kw">cluster</span> firm_id)</span>
<span id="cb3-16"><a href=""></a><span class="kw">estat</span> overid</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="iv-results" class="slide level2 smaller">
<h2>IV Results</h2>
<p>Effect of peer disclosure on the probability of disclosing</p>
<div class="columns">
<div class="column" style="width:55%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Estimator</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">First-stage F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS</td>
<td style="text-align: right;">0.813</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>2SLS, four instruments</td>
<td style="text-align: right;">0.478</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">32.3</td>
</tr>
<tr class="odd">
<td>GMM, four instruments</td>
<td style="text-align: right;">0.482</td>
<td style="text-align: right;">0.228</td>
<td style="text-align: right;">32.3</td>
</tr>
<tr class="even">
<td>2SLS, weak instrument (ROA only)</td>
<td style="text-align: right;">−41.8</td>
<td style="text-align: right;">814.3</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td>2SLS, invalid instrument</td>
<td style="text-align: right;">0.885</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">3,055</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<div class="fragment">
<p><strong>The truth</strong> = <strong>0.46</strong></p>
<ul>
<li class="fragment">OLS overstates herding by about 75%.</li>
<li class="fragment">2SLS recovers the truth, at the cost of a standard error more than 10 times larger.</li>
<li class="fragment">Paper: OLS 0.912, 2SLS 0.483 (SE 0.186).</li>
</ul>
</div>
<div class="fragment">
<ul>
<li class="fragment">The weak instrument produces nonsense.</li>
<li class="fragment">The invalid instrument has a very strong first stage and is still as biased as OLS.</li>
</ul>
</div>
</div></div>
</section>
<section id="diagnostics-and-their-limits" class="slide level2">
<h2>Diagnostics and Their Limits</h2>
<ul>
<li class="fragment"><strong>Endogeneity test</strong> (<code>estat endogenous</code>). Here <span class="math inline">\(p = 0.14\)</span>, even though OLS (0.81) and 2SLS (0.48) differ a lot. The 2SLS standard error is too large for the test to tell them apart.</li>
<li class="fragment"><strong>Hansen’s J</strong> (<code>estat overid</code>). With the four valid instruments, <span class="math inline">\(J = 1.03\)</span> (<span class="math inline">\(p = 0.79\)</span>). Paper: <span class="math inline">\(J = 4.54\)</span> (<span class="math inline">\(p &gt; .10\)</span>).</li>
<li class="fragment"><strong>But</strong> adding the invalid instrument to the four valid ones gives <span class="math inline">\(p = 0.40\)</span>. The test <strong>misses</strong> it.
<ul>
<li class="fragment">The J test only checks whether instruments agree with each other, and imprecise instruments cannot disagree significantly.</li>
</ul></li>
<li class="fragment">Passing these tests is weak evidence. The case for an instrument rests on the <strong>exclusion argument</strong>.</li>
</ul>
</section>
<section id="cautions-about-iv" class="slide level2">
<h2>Cautions About IV</h2>
<ul>
<li class="fragment"><strong>Exclusion is an argument, not a test.</strong> Explain why <span class="math inline">\(Z\)</span> cannot affect <span class="math inline">\(Y\)</span> except through <span class="math inline">\(D\)</span>, and what could break it.</li>
<li class="fragment"><strong>Weak instruments.</strong> Report the first-stage F and the first-stage coefficients, not only the second stage.</li>
<li class="fragment"><strong>Precision.</strong> IV standard errors are usually much larger than OLS ones (0.229 vs.&nbsp;0.020 here). Plan the sample accordingly.</li>
<li class="fragment"><strong>Interpretation.</strong> With heterogeneous effects, IV identifies the effect for units that respond to the instrument (a LATE), which may differ from the ATE.</li>
<li class="fragment"><strong>Marketing instruments.</strong> Many common instruments, such as lagged marketing variables and prices in other markets, have weak exclusion arguments; see Rossi (2014).</li>
<li class="fragment"><strong>Falsification.</strong> Shi et al.&nbsp;(2021) show no “herding” on randomly assigned false peers, a useful placebo.</li>
</ul>
</section></section>
<section>
<section id="wrapping-up" class="title-slide slide level1 center">
<h1>Wrapping Up</h1>

</section>
<section id="few-best-practices" class="slide level2 smaller">
<h2>Few Best Practices</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="matching-and-weighting">Matching and weighting</h3>
<ul>
<li class="fragment">Explain why <span class="math inline">\(X\)</span> captures the selection process. Gill et al.&nbsp;(2017) build their covariates from interviews with the app team.</li>
<li class="fragment">Use <strong>pre-treatment</strong> covariates only.</li>
<li class="fragment">Report the <strong>overlap plot</strong> and a <strong>balance table</strong> (raw and adjusted SMDs, variance ratios).</li>
<li class="fragment">State the <strong>estimand</strong> (ATE or ATT) and how trimming or calipers changed the sample.</li>
<li class="fragment">Show <strong>several estimators</strong> and a <strong>sensitivity analysis</strong> for unobserved confounding.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="instrumental-variables-1">Instrumental variables</h3>
<ul>
<li class="fragment">Make the <strong>exclusion argument</strong> explicit, using institutional detail.</li>
<li class="fragment">Report the <strong>first stage</strong> in full, with the first-stage F.</li>
<li class="fragment">Show the <strong>reduced form</strong>. If <span class="math inline">\(Z\)</span> does not move <span class="math inline">\(Y\)</span>, there is no effect to find.</li>
<li class="fragment">Report <strong>overidentification tests</strong> when possible, but do not lean on them.</li>
<li class="fragment">Run <strong>placebo or falsification tests</strong>, as Shi et al.&nbsp;(2021) do with false peer groups.</li>
</ul>
</div></div>
</section>
<section id="readings-matching" class="slide level2 smaller">
<h2>Readings: Matching</h2>
<ul>
<li><sub><sup> Gill, M., Sridhar, S., &amp; Grewal, R. (2017). Return on engagement initiatives: A study of a business-to-business mobile app. <em>Journal of Marketing</em>, 81(4), 45-66.</sup></sub></li>
<li><sub><sup> Rosenbaum, P. R., &amp; Rubin, D. B. (1983). The central role of the propensity score in observational studies for causal effects. <em>Biometrika</em>, 70(1), 41-55.</sup></sub></li>
<li><sub><sup> Rubin, D. B. (2008). For objective causal inference, design trumps analysis. <em>Annals of Applied Statistics</em>, 2(3), 808-840.</sup></sub></li>
<li><sub><sup> Imbens, G. W. (2004). Nonparametric estimation of average treatment effects under exogeneity: A review. <em>Review of Economics and Statistics</em>, 86(1), 4-29.</sup></sub></li>
<li><sub><sup> Stuart, E. A. (2010). Matching methods for causal inference: A review and a look forward. <em>Statistical Science</em>, 25(1), 1-21.</sup></sub></li>
<li><sub><sup> Austin, P. C. (2011). An introduction to propensity score methods for reducing the effects of confounding in observational studies. <em>Multivariate Behavioral Research</em>, 46(3), 399-424.</sup></sub></li>
<li><sub><sup> Hirano, K., Imbens, G. W., &amp; Ridder, G. (2003). Efficient estimation of average treatment effects using the estimated propensity score. <em>Econometrica</em>, 71(4), 1161-1189.</sup></sub></li>
<li><sub><sup> Crump, R. K., Hotz, V. J., Imbens, G. W., &amp; Mitnik, O. A. (2009). Dealing with limited overlap in estimation of average treatment effects. <em>Biometrika</em>, 96(1), 187-199.</sup></sub></li>
<li><sub><sup> Abadie, A., &amp; Imbens, G. W. (2016). Matching on the estimated propensity score. <em>Econometrica</em>, 84(2), 781-807.</sup></sub></li>
<li><sub><sup> King, G., &amp; Nielsen, R. (2019). Why propensity scores should not be used for matching. <em>Political Analysis</em>, 27(4), 435-454.</sup></sub></li>
<li><sub><sup> Abadie, A., &amp; Imbens, G. W. (2008). On the failure of the bootstrap for matching estimators. <em>Econometrica</em>, 76(6), 1537-1557.</sup></sub></li>
<li><sub><sup> VanderWeele, T. J., &amp; Ding, P. (2017). Sensitivity analysis in observational research: Introducing the E-value. <em>Annals of Internal Medicine</em>, 167(4), 268-274.</sup></sub></li>
<li><sub><sup> Oster, E. (2019). Unobservable selection and coefficient stability: Theory and evidence. <em>Journal of Business &amp; Economic Statistics</em>, 37(2), 187-204.</sup></sub></li>
<li><sub><sup> Goldfarb, A., Tucker, C., &amp; Wang, Y. (2022). Conducting research in marketing with quasi-experiments. <em>Journal of Marketing</em>, 86(3), 1-20.</sup></sub></li>
</ul>
</section>
<section id="readings-instrumental-variables" class="slide level2 smaller">
<h2>Readings: Instrumental Variables</h2>
<ul>
<li><sub><sup> Shi, H., Grewal, R., &amp; Sridhar, H. (2021). Organizational herding in advertising spending disclosures: Evidence and mechanisms. <em>Journal of Marketing Research</em>, 58(3), 515-538.</sup></sub></li>
<li><sub><sup> Angrist, J. D., &amp; Pischke, J.-S. (2009). <em>Mostly Harmless Econometrics: An Empiricist’s Companion</em>. Princeton University Press.</sup></sub></li>
<li><sub><sup> Imbens, G. W., &amp; Angrist, J. D. (1994). Identification and estimation of local average treatment effects. <em>Econometrica</em>, 62(2), 467-475.</sup></sub></li>
<li><sub><sup> Angrist, J. D., Imbens, G. W., &amp; Rubin, D. B. (1996). Identification of causal effects using instrumental variables. <em>Journal of the American Statistical Association</em>, 91(434), 444-455.</sup></sub></li>
<li><sub><sup> Manski, C. F. (1993). Identification of endogenous social effects: The reflection problem. <em>Review of Economic Studies</em>, 60(3), 531-542.</sup></sub></li>
<li><sub><sup> Staiger, D., &amp; Stock, J. H. (1997). Instrumental variables regression with weak instruments. <em>Econometrica</em>, 65(3), 557-586.</sup></sub></li>
<li><sub><sup> Stock, J. H., &amp; Yogo, M. (2005). Testing for weak instruments in linear IV regression. In D. W. K. Andrews &amp; J. H. Stock (Eds.), <em>Identification and Inference for Econometric Models</em> (pp.&nbsp;80-108). Cambridge University Press.</sup></sub></li>
<li><sub><sup> Lee, D. S., McCrary, J., Moreira, M. J., &amp; Porter, J. (2022). Valid t-ratio inference for IV. <em>American Economic Review</em>, 112(10), 3260-3290.</sup></sub></li>
<li><sub><sup> Rossi, P. E. (2014). Even the rich can make themselves poor: A critical examination of IV methods in marketing applications. <em>Marketing Science</em>, 33(5), 655-672.</sup></sub></li>
</ul>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-image="images/giantshoulder.jpg" data-background-size="cover" data-background-opacity="0.5" data-visibility="uncounted">
<h1></h1>
<div style="text-align: center">
<div style="margin-top: 150px; font-size: 3em; color: #990000;">
<p>Questions?</p>
</div>
<p>Thank You! <br> Email: <a href="mailto:shaikmu@iu.edu"><em>shaikmu@iu.edu</em></a></p>
</div>
</section>

<section>
<section id="appendix-difference-in-differences" class="title-slide slide level1 center" data-visibility="uncounted">
<h1>Appendix: Difference-in-Differences</h1>

</section>
<section id="about-this-appendix" class="slide level2" data-visibility="uncounted">
<h2>About This Appendix</h2>
<ul>
<li class="fragment">These slides are for <strong>self-study</strong>. Each step has a matching block of Stata code.</li>
<li class="fragment"><strong>Files</strong> (in the <code>stata/</code> folder)
<ul>
<li class="fragment"><code>05_simulate_did_data.do</code> creates the staggered-rollout data</li>
<li class="fragment"><code>06_did_demo.do</code> runs every estimate shown here</li>
</ul></li>
<li class="fragment"><strong>Part A.</strong> Two-period DiD on the app adoption data, as in Gill, Sridhar, and Grewal (2017).</li>
<li class="fragment"><strong>Part B.</strong> A staggered rollout of the app across sales regions: event studies, why standard two-way fixed effects (TWFE) can fail, and heterogeneity-robust estimators.</li>
<li class="fragment">As before, the data are simulated, so the <strong>true effects are known</strong>.</li>
</ul>
</section>
<section id="the-core-idea" class="slide level2" data-visibility="uncounted">
<h2>The Core Idea</h2>
<ul>
<li class="fragment">Simple comparisons each miss something
<ul>
<li class="fragment"><strong>Before vs.&nbsp;after</strong> for treated units ignores common time trends.</li>
<li class="fragment"><strong>Treated vs.&nbsp;untreated</strong> after treatment ignores selection.</li>
</ul></li>
<li class="fragment"><strong>DiD</strong> combines them, differencing away fixed group differences and common trends, <span class="math display">\[\widehat{\tau}_{DiD} = (\bar{Y}_{T,\text{post}} - \bar{Y}_{T,\text{pre}}) - (\bar{Y}_{C,\text{post}} - \bar{Y}_{C,\text{pre}})\]</span></li>
<li class="fragment"><strong>Key assumption: parallel trends.</strong> Without treatment, treated and control units would have changed by the same amount.
<ul>
<li class="fragment">It concerns an unobserved counterfactual, so it cannot be tested directly. Pre-treatment trends are indirect evidence.</li>
</ul></li>
</ul>
</section>
<section id="did-as-a-regression" class="slide level2" data-visibility="uncounted">
<h2>DiD as a Regression</h2>
<ul>
<li class="fragment">Two groups and two periods (Gill et al.&nbsp;2017, Equation 1), <span class="math display">\[S_{ijt} = \beta_0 + \beta_1 I_j + \beta_2 I_t + \beta_3 I_j \cdot I_t + \varepsilon_{ijt}\]</span>
<ul>
<li class="fragment"><span class="math inline">\(I_j = 1\)</span> for adopters (group effect), <span class="math inline">\(I_t = 1\)</span> after launch (time effect)</li>
<li class="fragment"><span class="math inline">\(\beta_3\)</span> is the DiD estimate</li>
</ul></li>
<li class="fragment"><strong>Inference.</strong> Cluster standard errors at the level at which treatment is assigned (Bertrand, Duflo, and Mullainathan 2004).</li>
<li class="fragment"><strong>Panel data, many periods.</strong> Two-way fixed effects, <span class="math display">\[Y_{it} = \alpha_i + \lambda_t + \delta D_{it} + \varepsilon_{it}\]</span>
<ul>
<li class="fragment"><span class="math inline">\(\alpha_i\)</span> unit effects, <span class="math inline">\(\lambda_t\)</span> period effects, <span class="math inline">\(D_{it} = 1\)</span> once unit <span class="math inline">\(i\)</span> is treated</li>
</ul></li>
</ul>
</section>
<section id="part-a-two-period-did-on-the-app-data" class="slide level2" data-visibility="uncounted">
<h2>Part A: Two-Period DiD on the App Data</h2>
<p>Average 15-month sales ($10,000)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Before launch</th>
<th style="text-align: right;">After launch</th>
<th style="text-align: right;">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adopters</td>
<td style="text-align: right;">83.02</td>
<td style="text-align: right;">105.14</td>
<td style="text-align: right;">22.12</td>
</tr>
<tr class="even">
<td>Nonadopters</td>
<td style="text-align: right;">77.57</td>
<td style="text-align: right;">74.61</td>
<td style="text-align: right;">−2.96</td>
</tr>
<tr class="odd">
<td><strong>Difference-in-differences</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>25.08</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<ul>
<li class="fragment">True effect for adopters: <strong>15.85</strong>. DiD overstates it by almost 60%.</li>
<li class="fragment">Parallel trends fails. Frequent buyers adopt more <strong>and</strong> grow faster without the app, so nonadopters are not a valid counterfactual trend.</li>
<li class="fragment">This 25.08 is the same as the naive estimate in the matching section, because the outcome there was already the change in sales.</li>
</ul>
</div>
</section>
<section id="two-period-did-in-stata" class="slide level2" data-visibility="uncounted">
<h2>Two-Period DiD in Stata</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href=""></a><span class="kw">use</span> app_adoption, <span class="kw">clear</span></span>
<span id="cb4-2"><a href=""></a></span>
<span id="cb4-3"><a href=""></a>* Stack pre and <span class="kw">post</span> sales: <span class="kw">two</span> <span class="bn">rows</span> per buyer</span>
<span id="cb4-4"><a href=""></a><span class="kw">rename</span> sales_pre  sales0</span>
<span id="cb4-5"><a href=""></a><span class="kw">rename</span> sales_post sales1</span>
<span id="cb4-6"><a href=""></a><span class="kw">reshape</span> <span class="kw">long</span> sales, i(buyer_id) j(<span class="kw">post</span>)</span>
<span id="cb4-7"><a href=""></a></span>
<span id="cb4-8"><a href=""></a>* The four <span class="kw">means</span> behind DiD</span>
<span id="cb4-9"><a href=""></a><span class="kw">table</span> app <span class="kw">post</span>, statistic(<span class="kw">mean</span> sales)</span>
<span id="cb4-10"><a href=""></a></span>
<span id="cb4-11"><a href=""></a>* DiD regression: the app#post coefficient is the DiD estimate</span>
<span id="cb4-12"><a href=""></a><span class="kw">regress</span> sales i.app##i.<span class="kw">post</span>, <span class="kw">vce</span>(<span class="kw">cluster</span> buyer_id)</span>
<span id="cb4-13"><a href=""></a></span>
<span id="cb4-14"><a href=""></a>* Same estimate with the built-<span class="kw">in</span> command</span>
<span id="cb4-15"><a href=""></a>xtset buyer_id <span class="kw">post</span></span>
<span id="cb4-16"><a href=""></a><span class="kw">generate</span> treat_post = app*<span class="kw">post</span></span>
<span id="cb4-17"><a href=""></a>xtdidregress (sales) (treat_post), <span class="fu">group</span>(buyer_id) time(<span class="kw">post</span>) <span class="kw">vce</span>(<span class="kw">cluster</span> buyer_id)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="covariates-levels-vs.-interactions" class="slide level2 smaller" data-visibility="uncounted">
<h2>Covariates: Levels vs.&nbsp;Interactions</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Specification</th>
<th style="text-align: right;">DiD estimate</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No covariates</td>
<td style="text-align: right;">25.08</td>
<td style="text-align: right;">1.43</td>
</tr>
<tr class="even">
<td>Covariates in levels</td>
<td style="text-align: right;">25.08</td>
<td style="text-align: right;">1.43</td>
</tr>
<tr class="odd">
<td>Covariates interacted with post</td>
<td style="text-align: right;">14.96</td>
<td style="text-align: right;">1.46</td>
</tr>
<tr class="even">
<td><strong>Truth</strong></td>
<td style="text-align: right;"><strong>15.85</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">Time-invariant covariates added <strong>in levels</strong> do not change the DiD estimate, because they do not change between periods. (Gill et al.&nbsp;report 16.01 with and without covariates.)</li>
<li class="fragment"><strong>Conditional parallel trends.</strong> Interacting each covariate with <code>post</code> lets the trend differ by buyer characteristics, which removes most of the bias here.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href=""></a><span class="kw">regress</span> sales i.app##i.<span class="kw">post</span> <span class="co">///</span></span>
<span id="cb5-2"><a href=""></a>    i.post##c.firm_size i.post##c.buyer_power i.post##c.competitiveness <span class="co">///</span></span>
<span id="cb5-3"><a href=""></a>    i.post##c.t0_sales i.post##c.t0_freq i.post##i.developing i.post##i.division, <span class="co">///</span></span>
<span id="cb5-4"><a href=""></a>    <span class="kw">vce</span>(<span class="kw">cluster</span> buyer_id)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li class="fragment">Matching or weighting on the change in sales (as in the seminar, and Gill et al.’s Appendix B) uses the same assumption.</li>
</ul>
</section>
<section id="part-b-a-staggered-rollout" class="slide level2" data-visibility="uncounted">
<h2>Part B: A Staggered Rollout</h2>
<ul>
<li class="fragment">Suppose the manufacturer rolls the app out <strong>region by region</strong>: regions 1 and 2 in quarter 5, regions 3 and 4 in quarter 7, regions 5 and 6 in quarter 9, and regions 7 and 8 never (during the 12 quarters).</li>
<li class="fragment">1,148 buyers, quarterly sales. The rollout order is unrelated to sales, so parallel trends holds.</li>
<li class="fragment">The effect <strong>grows with time since rollout</strong> and is <strong>larger in early regions</strong>. True ATT = <strong>2.31</strong>.</li>
</ul>

<img data-src="images/did_rollout_means.png" class="quarto-figure quarto-figure-center r-stretch" style="width:62.0%" alt="Average quarterly sales by rollout group, with the gap widening after each group's rollout quarter"></section>
<section id="standard-twfe-gets-it-wrong" class="slide level2" data-visibility="uncounted">
<h2>Standard TWFE Gets It Wrong</h2>
<ul>
<li class="fragment">TWFE regression with buyer and quarter fixed effects,</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb6-1"><a href=""></a><span class="kw">use</span> did_rollout, <span class="kw">clear</span></span>
<span id="cb6-2"><a href=""></a>xtset buyer_id <span class="fu">quarter</span></span>
<span id="cb6-3"><a href=""></a>xtdidregress (sales) (app_live), <span class="fu">group</span>(buyer_id) time(<span class="fu">quarter</span>) <span class="kw">vce</span>(<span class="kw">cluster</span> buyer_id)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li class="fragment"><strong>TWFE estimate: 1.01</strong> (SE 0.10). <strong>Truth: 2.31.</strong> TWFE recovers less than half the effect.</li>
<li class="fragment">Nothing is wrong with the data or with parallel trends. The problem is the estimator.</li>
<li class="fragment">With staggered timing <strong>and</strong> effects that change over time or across cohorts, TWFE is a weighted average of many 2×2 comparisons, some of which use <strong>already-treated</strong> units as controls (Goodman-Bacon 2021).</li>
</ul>
</section>
<section id="why-twfe-fails-goodman-bacon-decomposition" class="slide level2 smaller" data-visibility="uncounted">
<h2>Why TWFE Fails: Goodman-Bacon Decomposition</h2>
<div class="columns">
<div class="column" style="width:40%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Comparison</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treated vs.&nbsp;never treated</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="even">
<td>Treated earlier vs.&nbsp;later</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="odd">
<td>Treated later vs.&nbsp;earlier</td>
<td style="text-align: right;">−1.55</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="even">
<td><strong>TWFE (weighted average)</strong></td>
<td style="text-align: right;"><strong>1.01</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">“Later vs.&nbsp;earlier” uses early regions as controls after they are treated. Their growing effects are subtracted, giving <strong>negative</strong> estimates.</li>
<li class="fragment">In Stata, run <code>estat bdecomp</code> after <code>xtdidregress</code>.</li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/did_bdecomp.png" alt="Goodman-Bacon decomposition: each 2x2 comparison plotted against its weight; later-versus-earlier comparisons are negative"></p>
</div></div>
</section>
<section id="heterogeneity-robust-did" class="slide level2" data-visibility="uncounted">
<h2>Heterogeneity-Robust DiD</h2>
<ul>
<li class="fragment"><strong>Callaway and Sant’Anna (2021).</strong> Estimate a separate ATT for each <strong>cohort</strong> (rollout quarter) and <strong>period</strong>, comparing each cohort only with never-treated (or not-yet-treated) units, then average.</li>
<li class="fragment"><strong>Sun and Abraham (2021).</strong> An event-study regression with cohort-by-relative-time interactions, avoiding contaminated leads and lags.</li>
<li class="fragment"><strong>Extended TWFE (Wooldridge).</strong> TWFE with cohort-by-time interactions.</li>
<li class="fragment"><strong>In Stata 18 or later,</strong> <code>xthdidregress</code> estimates these (<code>ra</code>, <code>ipw</code>, <code>aipw</code>, <code>twfe</code>), and <code>estat aggregation</code> summarizes them.
<ul>
<li class="fragment">User-written alternatives include <code>csdid</code> and <code>eventstudyinteract</code> (SSC).</li>
</ul></li>
</ul>
</section>
<section id="event-study" class="slide level2" data-visibility="uncounted">
<h2>Event Study</h2>

<img data-src="images/did_event_study.png" class="r-stretch quarto-figure quarto-figure-center" alt="Event-study estimates: leads near zero before rollout, effects rising steadily after rollout"><ul>
<li class="fragment"><strong>Leads</strong> (before rollout) are near zero, consistent with parallel trends. <strong>Lags</strong> show the effect growing each quarter.</li>
</ul>
</section>
<section id="staggered-did-in-stata" class="slide level2" data-visibility="uncounted">
<h2>Staggered DiD in Stata</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href=""></a>* Callaway and Sant'Anna, doubly <span class="kw">robust</span> (AIPW), never-treated controls</span>
<span id="cb7-2"><a href=""></a>xthdidregress aipw (sales) (app_live), <span class="fu">group</span>(buyer_id)</span>
<span id="cb7-3"><a href=""></a></span>
<span id="cb7-4"><a href=""></a><span class="kw">estat</span> aggregation                   <span class="co">// overall ATT</span></span>
<span id="cb7-5"><a href=""></a><span class="kw">estat</span> aggregation, dynamic <span class="kw">graph</span>    <span class="co">// event study: leads and lags</span></span>
<span id="cb7-6"><a href=""></a><span class="kw">estat</span> aggregation, cohort           <span class="co">// ATT by rollout cohort</span></span>
<span id="cb7-7"><a href=""></a></span>
<span id="cb7-8"><a href=""></a>* Other estimators <span class="kw">in</span> the same command</span>
<span id="cb7-9"><a href=""></a>xthdidregress ra   (sales) (app_live), <span class="fu">group</span>(buyer_id)</span>
<span id="cb7-10"><a href=""></a>xthdidregress twfe (sales) (app_live), <span class="fu">group</span>(buyer_id)   <span class="co">// extended TWFE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="comparing-estimators-1" class="slide level2 smaller" data-visibility="uncounted">
<h2>Comparing Estimators</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Effect of the app on quarterly sales ($10,000)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Estimator</th>
<th style="text-align: right;">ATT</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard TWFE</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="even">
<td>Callaway–Sant’Anna (AIPW)</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="odd">
<td>Callaway–Sant’Anna (RA)</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="even">
<td>Extended TWFE</td>
<td style="text-align: right;">2.22</td>
<td style="text-align: right;">0.11</td>
</tr>
<tr class="odd">
<td><strong>Truth</strong></td>
<td style="text-align: right;"><strong>2.31</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<p>ATT by rollout cohort (Callaway–Sant’Anna)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Rollout quarter</th>
<th style="text-align: right;">ATT</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quarter 5</td>
<td style="text-align: right;">3.13</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td>Quarter 7</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="odd">
<td>Quarter 9</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.29</td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment">Early regions gain more, partly because they have had the app longer.</li>
</ul>
</div></div>
</section>
<section id="did-best-practices" class="slide level2" data-visibility="uncounted">
<h2>DiD Best Practices</h2>
<ul>
<li class="fragment">Explain the <strong>institutional context</strong>. Why was treatment timing unrelated to the outcome trend?</li>
<li class="fragment"><strong>Plot raw trends</strong> by group, and show an <strong>event study</strong> with leads.</li>
<li class="fragment">Run <strong>placebo tests</strong>: a fake treatment group, or fake treatment timing within the pre-period.</li>
<li class="fragment"><strong>Cluster</strong> standard errors at the level of treatment assignment.</li>
<li class="fragment">With <strong>staggered timing</strong>, report a heterogeneity-robust estimator alongside (or instead of) TWFE, and the Goodman-Bacon decomposition.</li>
<li class="fragment">If pre-trends are a concern, report how sensitive the result is to violations of parallel trends (Rambachan and Roth 2023).</li>
</ul>
</section>
<section id="readings-difference-in-differences" class="slide level2 smaller" data-visibility="uncounted">
<h2>Readings: Difference-in-Differences</h2>
<ul>
<li><sub><sup> Bertrand, M., Duflo, E., &amp; Mullainathan, S. (2004). How much should we trust differences-in-differences estimates? <em>Quarterly Journal of Economics</em>, 119(1), 249-275.</sup></sub></li>
<li><sub><sup> Goodman-Bacon, A. (2021). Difference-in-differences with variation in treatment timing. <em>Journal of Econometrics</em>, 225(2), 254-277.</sup></sub></li>
<li><sub><sup> Callaway, B., &amp; Sant’Anna, P. H. C. (2021). Difference-in-differences with multiple time periods. <em>Journal of Econometrics</em>, 225(2), 200-230.</sup></sub></li>
<li><sub><sup> Sun, L., &amp; Abraham, S. (2021). Estimating dynamic treatment effects in event studies with heterogeneous treatment effects. <em>Journal of Econometrics</em>, 225(2), 175-199.</sup></sub></li>
<li><sub><sup> Baker, A. C., Larcker, D. F., &amp; Wang, C. C. Y. (2022). How much should we trust staggered difference-in-differences estimates? <em>Journal of Financial Economics</em>, 144(2), 370-395.</sup></sub></li>
<li><sub><sup> Roth, J., Sant’Anna, P. H. C., Bilinski, A., &amp; Poe, J. (2023). What’s trending in difference-in-differences? A synthesis of the recent econometrics literature. <em>Journal of Econometrics</em>, 235(2), 2218-2244.</sup></sub></li>
<li><sub><sup> Rambachan, A., &amp; Roth, J. (2023). A more credible approach to parallel trends. <em>Review of Economic Studies</em>, 90(5), 2555-2591.</sup></sub></li>
<li><sub><sup> Goldfarb, A., Tucker, C., &amp; Wang, Y. (2022). Conducting research in marketing with quasi-experiments. <em>Journal of Marketing</em>, 86(3), 1-20.</sup></sub></li>
</ul>
<script>
// Hide the slide number on uncounted slides (thank-you and appendix)
window.addEventListener("load", function () {
  function toggleNumber() {
    var number = document.querySelector(".reveal .slide-number");
    var slide = Reveal.getCurrentSlide();
    if (!number || !slide) return;
    var stack = slide.parentElement && slide.parentElement.closest("section");
    var uncounted = slide.getAttribute("data-visibility") === "uncounted" ||
      (stack && stack.getAttribute("data-visibility") === "uncounted");
    number.style.visibility = uncounted ? "hidden" : "visible";
  }
  Reveal.on("ready", toggleNumber);
  Reveal.on("slidechanged", toggleNumber);
  toggleNumber();
});
</script>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/kelley-marketing-revised-removebg-preview.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Causal_FSU_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Causal_FSU_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Causal_FSU_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Causal_FSU_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>